export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const CHANGE_COMPLETED_STATE = "CHANGE_COMPLETED_STATE";
export const GET_TASKS_LOADED = "GET_TASKS_LOADED";
export const CHANGE_ISEDIT_STATE = "CHANGE_ISEDIT_STATE";
export const SET_EDIT_OBJECT = "SET_EDIT_OBJECT";
export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";
